### ISSUE TITLE
Audio not working

### ISSUE THREAD

**Issue by StefanNienhuis** [invano/airplay2-receiver#1]
Hi, first of all, nice work man! I'm having an issue though, it doesn't play any audio. It shows up in my Airplay list as an ap2 device, I can connect to it, it logs something when I change the volume, but no audio is playing. Has this not been implemented yet, or is there something wrong on my end?

**Comment by invano** [comment]
It doesn't work with Apple Music and any other source relying on buffered audio, unless you implement what's missing, including an AAC-LC decoder.

**Comment by noelhibbard** [comment]
Most apps I tested with used buffered audio. Spotify uses real time audio so you should get output with that.

**Comment by invano** [comment]
Only tried with Apple Music, YouTube and Spotify so far. Buffered the first, real time the two.

**Comment by noelhibbard** [comment]
I noticed in your docs that YouTube was realtime but when I tried it did buffered audio. My test was with the YouTube app. Didn't try YouTube in a browser though.
